version: "3"
services:
  app:
    build: app
    environment:
      - PORT=8080
  postgres:
    build: postgres
    environment:
      - POSTGRES_USER=cowmoo
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
  nginx:
    build: nginx
    ports:
      - "8080:8080"
  cas:
    build: cas
